- alignment/Makefile
May help fix some internal pacbio build issues.
> Only set HTSLIB_INCLUDE if not already set

- Makefile
- README.md
- alignment/simple.mk
- pbdata/Makefile
- pbdata/mklibconfig.sh
Re-creating this file would cause make to redo things repeatedly.
Make is timestamp-based. A more sophisticated build system would use checksums and would include the full build rules, but that's hard. This is a fair compromise to help make do what make does best.
> libconfig.h

- configure.py
Fixes this problem, since GNU make provides a default `CXX=g++`:
```
libblasr.so: undefined reference to `memcpy@GLIBC_2.14'
libblasr.so: undefined reference to `clock_gettime@GLIBC_2.17'
```
> use provided CXX

- pbdata/FASTQSequence.cpp
> Use virtual qStart/qEnd when reading ccs reads.

- configure.py
- makefile
- pbdata/makefile
The complexity here is because we sometimes build the
subdirs separately, and sometimes together. So we don't
know whether configure.py is run 3 times in 3 dirs, or just
once. So we don't know in advance where to put libconfig.h.
A better solution might be an 'install' rule. Soon.
> copy libconfig.h into build directory

- hdf/makefile
vpath works correctly only when the source filenames do not include directories.
re: PacificBiosciences/pith#6
@mjhsieh, With this change, your 'make clean' is no longer needed, but it doesn't hurt.
> Fix outputdir

- alignment/format/BAMPrinter.hpp
- alignment/format/BAMPrinterImpl.hpp
- pbdata/SMRTSequence.cpp
Here is the full *bam_concordant* branch. The code at the tip is identical to ylipacbio/blasr_libcpp@598b674 (aside from whitespace changes), which is the tip of *bam_concordant*.
EDIT: The unittests passed after a clean rebuild. Something is wrong with the dependencies. (Maybe the unittest dir is missing a make-depend.)
> bam_concordant

- alignment/files/ReaderAgglomerate.hpp
- hdf/HDFRegionTableReader.hpp
- pbdata/CCSSequence.hpp
Revert changes to CCSSequence function SubreadStart, SubreadEnd, SubreadLength.
ReaderAgglomerate.hpp: update pbbam header file because pbbam has been refactored in p4 CL 163004
HDFRegionTableReader: removed a warning
> More changes

- pbdata/FASTAReader.cpp
- unittest/pbdata/DNASequence_gtest.cpp
This bug predates any of yli's recent changes. E.g. @963859fcca47feaec7c47523157cf1c2888bad69, used in PacificBiosciences/blasr@2551ead:
```
==126360== Mismatched free() / delete / delete []
==126360==    at 0x4C2C0F1: operator delete(void*) (vg_replace_malloc.c:507)
==126360==    by 0x5643626: FASTAReader::ReadTitle(long&, FASTASequence&) (FASTAReader.cpp:220)
==126360==    by 0x564384F: FASTAReader::GetNext(FASTASequence&) (FASTAReader.cpp:268)
==126360==    by 0x51B1823: ReaderAgglomerate::GetNext(CCSSequence&) (ReaderAgglomerate.cpp:420)
==126360==    by 0x4133BC: main (in /home/UNIXHOME/cdunn/repo/gh/blasr/utils/toAfg)
==126360==  Address 0x78818c0 is 0 bytes inside a block of size 6 alloc'd
==126360==    at 0x4C2B76A: operator new[](unsigned long) (vg_replace_malloc.c:389) …
```
> Array delete bug

- alignment/makefile
- alignment/query/PbiFilterZmwGroupQuery.cpp
- alignment/query/PbiFilterZmwGroupQuery.h
- alignment/query/SequentialZmwGroupQuery.cpp
- alignment/query/SequentialZmwGroupQuery.h
Moved  bug 28882 p4 CL 164057 to blasr_libcpp.
SequentialZmwGroupQuery returns a vector of bam records of a zmw at a time.
PbiFilterZmwGroupQuery returns a vector of bam records of a zmw at a time and respects filters in dataset.
Note that both classes require bam records of a zmw to be stored next to one another.
Note that we will switch to Derek's pbbam APIs when they are available.
> Add SequentialZmwGroupQuery and PbiFilterZmwGroupQuery

- unittest/alignment/files/ReaderAgglomerate_gtest.cpp
- unittest/makefile
`ReaderAgglomerate` and `FileUtils` now pass.
See #80.
> Revive some gtests

- hdf/HDFPulseCallsWriter.cpp
- hdf/HDFPulseCallsWriter.hpp
Internal Bam spec updated, tag sf added.
No longer use PrePulseFrames and PulseWidthFrames to compute StartFrame. Use tag 'sf' instead.
> Use bam tag 'sf' StartFrame to build PulseCalls/StartFrame.

- hdf/HDFPulseCallsWriter.cpp
- hdf/HDFPulseCallsWriter.hpp
Fix pkmean and pkmid signals. 
pbbam public apis (i.e., BamReacord.PkMean() and BamRecord.PkMid()) still return incorrect signals, let's fall back to lower-level api instead.
> Fix pkmean and pkmid signals

- hdf/HDFPulseWriter.cpp
Add fake dataset QualityValue back plx.h5
/PulseData/BaseCalls.
> Fix bam2plx jenkins test:

- alignment/suffixarray/ssort.hpp
Skip (abort()) infinite loop.
resolves #121 
(Discussed w/ yli.)
> Avoid compiler warning

- alignment/makefile
- hdf/makefile
- pbdata/makefile
This simple change makes the compile lines much easier to read (and more easily cached, if that matters). These 3 libs *are* in the same, repo, so they may as well use relative paths. Anyway, I think the present change is really a no-op, since it applies to files in CURDIR.
> Build relative paths

- alignment/MappingMetrics.cpp
- alignment/algorithms/alignment/AlignmentUtilsImpl.hpp
- alignment/algorithms/alignment/ExtendAlign.hpp
- alignment/algorithms/alignment/IDSScoreFunction.hpp
- alignment/algorithms/alignment/KBandAlign.hpp
- alignment/algorithms/alignment/QualityValueScoreFunction.cpp
- alignment/algorithms/anchoring/FindMaxIntervalImpl.hpp
- alignment/algorithms/anchoring/LongestIncreasingSubsequenceImpl.hpp
- alignment/bwt/BWT.hpp
- alignment/files/FragmentCCSIterator.cpp
- alignment/format/SAMHeaderPrinter.cpp
- alignment/format/SAMHeaderPrinter.hpp
- alignment/makefile
- alignment/statistics/StatUtilsImpl.hpp
- alignment/suffixarray/SuffixArray.hpp
- alignment/tuples/DNATupleImpl.hpp
- hdf/BufferedHDF2DArrayImpl.hpp
- hdf/BufferedHDFArrayImpl.hpp
- hdf/HDFArray.hpp
- hdf/HDFRegionsWriter.cpp
- hdf/HDFWriteBuffer.hpp
- hdf/HDFWriterBase.hpp
- hdf/makefile
- pbdata/CompressedSequenceImpl.hpp
- pbdata/FASTQSequence.cpp
- pbdata/Types.h
- pbdata/matrix/MatrixImpl.hpp
- pbdata/metagenome/SequenceIndexDatabaseImpl.hpp
- pbdata/sam/SAMAlignment.cpp
Also, this suppresses some warnings for hidden virtual methods, but those might actually be errors! So somebody should drop `-Wno-overloaded-virtual` and address those.
I've also added the `PB_UNUSED()` macro, to make it easier to find unused variables (in case anybody wants to fix these for reals).
> FIx clang warnings

- alignment/format/SAMHeaderPrinter.hpp
```
In file included from format/SAMHeaderPrinter.cpp:2:0:
format/SAMHeaderPrinter.hpp: In instantiation of ‘void SAMHeaderGroups<T>::Append(const std::vector<T_Value>&) [with T = std::basic_string<char>]’:
format/SAMHeaderPrinter.cpp:441:44:   required from here
format/SAMHeaderPrinter.hpp:281:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for(int i = 0; i < groups.size(); i++) {
^
```
> either declare `i` unsigned int or this patch

- alignment/algorithms/alignment/ExtendAlign.hpp
- alignment/algorithms/alignment/KBandAlign.hpp
added ```#include <iosfwd>```.
This resolves the issue where ```make build-submodule`` was error out with g++6.0
> Added missing headers

- hdf/HDFPulseCallsWriter.cpp
Based on test, pbbam does not seem to fix bug 29381, so
pbbam.BamRecord.pkmean() and pkmid() functions are not
reliable at this point. Have to bring code using
lower-level API for fetching pkmid and pkmean back.
> Revert code to fetch pkmid/pkmean.

- pbdata/CommandLineParser.cpp
This would have avoided some confusion in
PacificBiosciences/blasr#245
Without this change:
```
$ blasr --woo
...
ERROR: -woo is not a valid option.
```
With this change:
```
$ blasr --woo
...
ERROR: --woo is not a valid option.
```
> Show actual flag in error messages

- hdf/HDFZMWWriter.cpp
- pbdata/SMRTSequence.cpp
"the upper bits are the X-position and the lower bits are the Y-position. Appears reversed." - SEQ-315
> Contribution from John N.

- alignment/makefile
- pbdata/makefile
UNIX `find` works differently on OSX, where it keeps any trailing slash
on its directory argument.
fixes PacificBiosciences/pbdagcon#59
(This is on the new `pbdagcon` branch because there are a lot of changes that are not yet used in pbdagcon. Someone will have to integrate this fix later, if still needed.)
> Avoid trailing slash in UNIX find arg

- alignment/algorithms/sorting/LightweightSuffixArray.cpp
@ylipacbio  is this okay?  the error output is polluting smrtlink logs whenever a FASTA reference file is imported.  it would be even better to use standard logging functions but i'm going for the quick fix right now.
> progress output should go to cout, not cerr
