PacificBiosciences/blasr_libcpp

alignment/Makefile
pbdata/Makefile

Herb, I copied these from
```
smrtanalysis/build/3.x/buildctl/pacbio/libpbdata/Makefile.tmp.buildctl
/libblasr/
```

trying to get shared libraries in the Perforce build

---

.travis.yml
alignment/Makefile
hdf/Makefile

Not totally ideal, but points us in the right direction I think.  There are some problems with the way some of the paths are resolved in common.mk.  See my commits for details.

Get past the hdf nonsense

---

pbdata/Makefile

the trick is to use a tab here instead of 4 spaces

fixes PacificBiosciences/blasr#65

---

.gitignore
alignment/build.mk
configure.py
hdf/build.mk
pbdata/build.mk
rules.mk
unittest/.gitignore

I've tested this with mobs.
* accept make-style env-args
* patsubst ${INCLUDES}
This lets us avoid some if-statements.
* unittest is not done yet
If this looks good, then I'll ask Vladimir to do this for blasr and pbdagcon too. We'll discuss it soon.

should work both within pacbio and externally

---

alignment/format/BAMPrinter.hpp
alignment/format/BAMPrinterImpl.hpp
alignment/format/SAMHeaderPrinter.cpp
alignment/format/SAMPrinter.cpp
alignment/format/SAMPrinter.hpp
pbdata/StringUtils.cpp
pbdata/StringUtils.hpp
pbdata/sam/SAMReaderImpl.hpp
pbdata/utils/SMRTReadUtils.cpp
unittest/pbdata/StringUtils_gtest.cpp

Use cigar X and = instead of M.

BAM conforming to SPEC v 3.0b7

---

configure.py

This change is used by new makefiles in blasr. Otherwise, harmless.

to help use blasr outside mobs

---

.gitignore
alignment/makefile
configure.py
hdf/makefile
pbdata/makefile
rules.mk

use -install_name instead of -soname on OSX

---

alignment/datastructures/alignment/FilterCriteria.cpp

* PacificBiosciences/blasr#105
* http://stackoverflow.com/questions/8016780/undefined-reference-to-static-constexpr-char

possible bug-fix

---

hdf/BufferedHDF2DArrayImpl.hpp
hdf/HDFWriterBase.cpp
hdf/HDFWriterBase.hpp
hdf/HDFZMWMetricsWriter.cpp
hdf/HDFZMWMetricsWriter.hpp
hdf/HDFZMWWriter.cpp
hdf/HDFZMWWriter.hpp
pbdata/PacBioDefs.h
pbdata/SMRTSequence.cpp

Support writing ZMW/HoleStatus and ZMWMetrics/Productivity.

Update blasr libcpp

---

alignment/algorithms/anchoring/MapBySuffixArrayImpl.hpp
alignment/files/ReaderAgglomerate.cpp
alignment/format/BAMPrinterImpl.hpp
alignment/format/SAMPrinterImpl.hpp
hdf/HDFBasReader.hpp
hdf/HDFCmpFile.hpp
hdf/HDFZMWWriter.cpp
pbdata/FASTASequence.cpp
pbdata/FASTASequence.hpp
pbdata/FASTQSequence.cpp
pbdata/FASTQSequence.hpp
pbdata/SMRTSequence.cpp
pbdata/SMRTSequence.hpp
pbdata/reads/BaseFile.cpp
pbdata/utils/SMRTTitle.hpp
unittest/pbdata/CCSSequence_gtest.cpp
unittest/pbdata/SMRTSequence_gtest.cpp

Identical to ylipacbio/blasr_libcpp@8b855dc409d09466e638690feb555c9ef31b7a0a

SMRTSequence: modifications to access functions

---

hdf/HDFBasReader.hpp
hdf/HDFRegionTableReader.cpp
hdf/HDFRegionTableReader.hpp
pbdata/reads/ReadInterval.hpp
pbdata/reads/RegionAnnotation.cpp
pbdata/reads/RegionAnnotation.hpp
pbdata/reads/RegionAnnotations.cpp
pbdata/reads/RegionAnnotations.hpp
pbdata/reads/RegionTable.cpp
pbdata/reads/RegionTable.hpp
pbdata/reads/RegionTypeMap.cpp
pbdata/reads/RegionTypeMap.hpp
unittest/alignment/files/CCSIterator_gtest.cpp
unittest/alignment/files/FragmentCCSIterator_gtest.cpp
unittest/pbdata/reads/RegionAnnotations_gtest.cpp
unittest/pbdata/reads/RegionTypeMap_gtest.cpp

Unittests still pass. They begin to fail at the *next* commit on branch *bam_concordant*, so this is a good check-point for review.

Some region table refactoring

---

alignment/files/FragmentCCSIterator.cpp
alignment/utils/RegionUtils.cpp
alignment/utils/RegionUtils.hpp
alignment/utils/RegionUtilsImpl.hpp
hdf/HDFAtom.cpp
hdf/HDFAtom.hpp
hdf/HDFBasReader.hpp
hdf/HDFRegionTableReader.cpp
hdf/HDFRegionTableReader.hpp
pbdata/reads/RegionTable.cpp
pbdata/reads/RegionTable.hpp
unittest/alignment/files/FragmentCCSIterator_gtest.cpp
unittest/alignment/files/FragmentCCSIterator_other_gtest.cpp
unittest/alignment/utils/RegionUtils_gtest.cpp
unittest/pbdata/reads/RegionAnnotations_gtest.cpp

Unittests pass here. Maybe this is a good check-point for review.

RegionTable: Major changes to API

---

pbdata/CCSSequence.cpp
pbdata/CCSSequence.hpp

CCSSequence: minor change

---

hdf/HDFRegionTableReader.cpp
pbdata/reads/RegionAnnotations.cpp
pbdata/reads/RegionTable.cpp

Old assert convention did not work on macosx.

---

alignment/makefile
configure.py
hdf/makefile
makefile
pbdata/makefile
rules.mk
unittest/makefile

Makefile changes

---

alignment/files/ReaderAgglomerate.hpp
alignment/query/PbiFilterZmwGroupQuery.cpp
alignment/query/PbiFilterZmwGroupQuery.h
alignment/query/SequentialZmwGroupQuery.cpp
alignment/query/SequentialZmwGroupQuery.h

Update header files in SequentialZmwGroupQuery and PbiFilterZmwGroupQuery since pbbam has updated.

Update header files in SequentialZmwGroupQuery and PbiFilterZmwGroupQuery.

---

hdf/HDFBaseCallsWriter.cpp
hdf/HDFBaseCallsWriter.hpp
hdf/HDFPulseCallsWriter.cpp
hdf/HDFPulseCallsWriter.hpp
hdf/HDFPulseWriter.cpp
hdf/HDFPulseWriter.hpp
hdf/HDFWriterBase.cpp
hdf/HDFWriterBase.hpp
hdf/HDFZMWWriter.cpp
hdf/HDFZMWWriter.hpp
pbdata/PacBioDefs.h

* HDFWriterBase.hpp make virtual deleter.
* Added HDFPulseCallsWriter, which writes data to PulseData/PulseCalls.
* Added HDFPulseWriter, which writes a plx.h5 file.
* Modified HDFZMWWriter to write ZMW under /PulseData/PulseCalls

Added HDF writers for bam2plx

---

alignment/format/BAMPrinter.hpp
alignment/format/BAMPrinterImpl.hpp
alignment/format/SAMPrinter.cpp
alignment/format/SAMPrinter.hpp
alignment/format/SAMPrinterImpl.hpp
unittest/alignment/format/SAMPrinter_gtest.cpp
unittest/makefile

This should be identical to request #89 which can not be reopened.

Cigar string, allow adjacent indels ON|OFF.

---

hdf/HDFBaseCallsWriter.cpp
hdf/HDFBaseCallsWriter.hpp
hdf/HDFPulseCallsWriter.cpp
hdf/HDFZMWWriter.cpp
pbdata/PacBioDefs.h

Update HDFPulseCallerWriter since internal BAM Spec has been update:
Type of LabelQV, AltLabelQV and PulseMergeQV changed from B:C to Z.
Fix PulseCalls/IsPulse
Add BaseCalls/PulseIndex

Update HDFPulseCallsWriter since internal bam spec has been updated.

---

hdf/HDFAtom.cpp
hdf/HDFAtom.hpp
hdf/HDFScanDataWriter.cpp
hdf/HDFScanDataWriter.hpp
pbdata/Enumerations.h
pbdata/reads/AcqParams.cpp
pbdata/reads/AcqParams.hpp
pbdata/reads/ScanData.cpp
pbdata/reads/ScanData.hpp

Add to attributes of /ScanData/AcqParams:
* AduGain float 1.0
* CameraGain float 1.0
* CameraType int 0
* HotStartFrame uint 0
* LaserOnFrame uint 
Change attribute FrameRate to 80.047035 (assuming this is consistent)
Add to attributes of /ScanData/RunInfo (based on what I found in a recent trace
file)
* InstrumentName string sequel
* PlatformId uint 4
* PlatformName string SequelAlpha
* MovieName string (whatever the movie name actually is, e.g., basename of bam
file)
*Modify*( to attributes of /ScanData/DyeSet
* NumAnalog uint16 4 (instead of uint32)

For pulse recognizer

---

hdf/HDFPulseCallsWriter.cpp
hdf/HDFPulseCallsWriter.hpp
hdf/HDFWriterBase.hpp
hdf/HDFZMWWriter.cpp

Change ZMW/BaselineSigma, BaselineLevel, SignalLevel, SignalSigma to 2D Array.

Change Chi2 and MeanSignal to 2D Array.

---

alignment/files/ReaderAgglomerate.cpp
pbdata/SMRTSequence.cpp
pbdata/SMRTSequence.hpp
pbdata/qvs/QualityValueVectorImpl.hpp

ReaderAgglomerate: skip reading bad bam reads.
Also trimmed some ending spaces from source file.

Bug30566 skip bad reads

---

alignment/files/ReaderAgglomerate.cpp
alignment/files/ReaderAgglomerate.hpp

Support -noSplitSubreads option  for .bam and .xml files

polymerase bam support

---

alignment/algorithms/alignment/IDSScoreFunction.cpp
pbdata/SMRTSequence.cpp
pbdata/SMRTSequence.hpp
pbdata/qvs/QualityValueVector.hpp
pbdata/qvs/QualityValueVectorImpl.hpp
unittest/pbdata/SMRTSequence_gtest.cpp
unittest/pbdata/qvs/QualityValueVector_gtest.cpp

Fix non-determined behaviour introduced because of uninitialized insertionQVs.

Fix non deterministic

---

alignment/MappingMetrics.hpp

Our previous apple hack is not needed on sierra.

Mac os x version 10 12
